#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="student_schedule")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_register(tbl_register instance);
  partial void Updatetbl_register(tbl_register instance);
  partial void Deletetbl_register(tbl_register instance);
  partial void Inserttbl_attend(tbl_attend instance);
  partial void Updatetbl_attend(tbl_attend instance);
  partial void Deletetbl_attend(tbl_attend instance);
  partial void Inserttbl_login(tbl_login instance);
  partial void Updatetbl_login(tbl_login instance);
  partial void Deletetbl_login(tbl_login instance);
  partial void Inserttbl_schedule(tbl_schedule instance);
  partial void Updatetbl_schedule(tbl_schedule instance);
  partial void Deletetbl_schedule(tbl_schedule instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["student_scheduleConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_register> tbl_registers
	{
		get
		{
			return this.GetTable<tbl_register>();
		}
	}
	
	public System.Data.Linq.Table<tbl_attend> tbl_attends
	{
		get
		{
			return this.GetTable<tbl_attend>();
		}
	}
	
	public System.Data.Linq.Table<tbl_login> tbl_logins
	{
		get
		{
			return this.GetTable<tbl_login>();
		}
	}
	
	public System.Data.Linq.Table<tbl_schedule> tbl_schedules
	{
		get
		{
			return this.GetTable<tbl_schedule>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_register")]
public partial class tbl_register : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _stud_id;
	
	private string _stud_name;
	
	private string _stud_class;
	
	private string _stud_email;
	
	private string _stud_password;
	
	private string _stud_pic;
	
	private string _user_type;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstud_idChanging(int value);
    partial void Onstud_idChanged();
    partial void Onstud_nameChanging(string value);
    partial void Onstud_nameChanged();
    partial void Onstud_classChanging(string value);
    partial void Onstud_classChanged();
    partial void Onstud_emailChanging(string value);
    partial void Onstud_emailChanged();
    partial void Onstud_passwordChanging(string value);
    partial void Onstud_passwordChanged();
    partial void Onstud_picChanging(string value);
    partial void Onstud_picChanged();
    partial void Onuser_typeChanging(string value);
    partial void Onuser_typeChanged();
    #endregion
	
	public tbl_register()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int stud_id
	{
		get
		{
			return this._stud_id;
		}
		set
		{
			if ((this._stud_id != value))
			{
				this.Onstud_idChanging(value);
				this.SendPropertyChanging();
				this._stud_id = value;
				this.SendPropertyChanged("stud_id");
				this.Onstud_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_name", DbType="VarChar(50)")]
	public string stud_name
	{
		get
		{
			return this._stud_name;
		}
		set
		{
			if ((this._stud_name != value))
			{
				this.Onstud_nameChanging(value);
				this.SendPropertyChanging();
				this._stud_name = value;
				this.SendPropertyChanged("stud_name");
				this.Onstud_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_class", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string stud_class
	{
		get
		{
			return this._stud_class;
		}
		set
		{
			if ((this._stud_class != value))
			{
				this.Onstud_classChanging(value);
				this.SendPropertyChanging();
				this._stud_class = value;
				this.SendPropertyChanged("stud_class");
				this.Onstud_classChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_email", DbType="VarChar(50)")]
	public string stud_email
	{
		get
		{
			return this._stud_email;
		}
		set
		{
			if ((this._stud_email != value))
			{
				this.Onstud_emailChanging(value);
				this.SendPropertyChanging();
				this._stud_email = value;
				this.SendPropertyChanged("stud_email");
				this.Onstud_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_password", DbType="VarChar(50)")]
	public string stud_password
	{
		get
		{
			return this._stud_password;
		}
		set
		{
			if ((this._stud_password != value))
			{
				this.Onstud_passwordChanging(value);
				this.SendPropertyChanging();
				this._stud_password = value;
				this.SendPropertyChanged("stud_password");
				this.Onstud_passwordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stud_pic", DbType="VarChar(MAX)")]
	public string stud_pic
	{
		get
		{
			return this._stud_pic;
		}
		set
		{
			if ((this._stud_pic != value))
			{
				this.Onstud_picChanging(value);
				this.SendPropertyChanging();
				this._stud_pic = value;
				this.SendPropertyChanged("stud_pic");
				this.Onstud_picChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_type", DbType="VarChar(50)")]
	public string user_type
	{
		get
		{
			return this._user_type;
		}
		set
		{
			if ((this._user_type != value))
			{
				this.Onuser_typeChanging(value);
				this.SendPropertyChanging();
				this._user_type = value;
				this.SendPropertyChanged("user_type");
				this.Onuser_typeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_attend")]
public partial class tbl_attend : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _attend_id;
	
	private string _attend_curr_date;
	
	private string _attend_class;
	
	private string _attend_attendance;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onattend_idChanging(int value);
    partial void Onattend_idChanged();
    partial void Onattend_curr_dateChanging(string value);
    partial void Onattend_curr_dateChanged();
    partial void Onattend_classChanging(string value);
    partial void Onattend_classChanged();
    partial void Onattend_attendanceChanging(string value);
    partial void Onattend_attendanceChanged();
    #endregion
	
	public tbl_attend()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attend_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int attend_id
	{
		get
		{
			return this._attend_id;
		}
		set
		{
			if ((this._attend_id != value))
			{
				this.Onattend_idChanging(value);
				this.SendPropertyChanging();
				this._attend_id = value;
				this.SendPropertyChanged("attend_id");
				this.Onattend_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attend_curr_date", DbType="VarChar(50)")]
	public string attend_curr_date
	{
		get
		{
			return this._attend_curr_date;
		}
		set
		{
			if ((this._attend_curr_date != value))
			{
				this.Onattend_curr_dateChanging(value);
				this.SendPropertyChanging();
				this._attend_curr_date = value;
				this.SendPropertyChanged("attend_curr_date");
				this.Onattend_curr_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attend_class", DbType="VarChar(50)")]
	public string attend_class
	{
		get
		{
			return this._attend_class;
		}
		set
		{
			if ((this._attend_class != value))
			{
				this.Onattend_classChanging(value);
				this.SendPropertyChanging();
				this._attend_class = value;
				this.SendPropertyChanged("attend_class");
				this.Onattend_classChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attend_attendance", DbType="VarChar(50)")]
	public string attend_attendance
	{
		get
		{
			return this._attend_attendance;
		}
		set
		{
			if ((this._attend_attendance != value))
			{
				this.Onattend_attendanceChanging(value);
				this.SendPropertyChanging();
				this._attend_attendance = value;
				this.SendPropertyChanged("attend_attendance");
				this.Onattend_attendanceChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_login")]
public partial class tbl_login : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _log_id;
	
	private string _log_email;
	
	private string _log_password;
	
	private string _user_type;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlog_idChanging(int value);
    partial void Onlog_idChanged();
    partial void Onlog_emailChanging(string value);
    partial void Onlog_emailChanged();
    partial void Onlog_passwordChanging(string value);
    partial void Onlog_passwordChanged();
    partial void Onuser_typeChanging(string value);
    partial void Onuser_typeChanged();
    #endregion
	
	public tbl_login()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int log_id
	{
		get
		{
			return this._log_id;
		}
		set
		{
			if ((this._log_id != value))
			{
				this.Onlog_idChanging(value);
				this.SendPropertyChanging();
				this._log_id = value;
				this.SendPropertyChanged("log_id");
				this.Onlog_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_email", DbType="VarChar(50)")]
	public string log_email
	{
		get
		{
			return this._log_email;
		}
		set
		{
			if ((this._log_email != value))
			{
				this.Onlog_emailChanging(value);
				this.SendPropertyChanging();
				this._log_email = value;
				this.SendPropertyChanged("log_email");
				this.Onlog_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_password", DbType="VarChar(50)")]
	public string log_password
	{
		get
		{
			return this._log_password;
		}
		set
		{
			if ((this._log_password != value))
			{
				this.Onlog_passwordChanging(value);
				this.SendPropertyChanging();
				this._log_password = value;
				this.SendPropertyChanged("log_password");
				this.Onlog_passwordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_type", DbType="VarChar(50)")]
	public string user_type
	{
		get
		{
			return this._user_type;
		}
		set
		{
			if ((this._user_type != value))
			{
				this.Onuser_typeChanging(value);
				this.SendPropertyChanging();
				this._user_type = value;
				this.SendPropertyChanged("user_type");
				this.Onuser_typeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_schedule")]
public partial class tbl_schedule : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _sch_id;
	
	private string _sch_day;
	
	private string _sch_date;
	
	private string _sch_time;
	
	private string _sch_class;
	
	private string _sch_class_name;
	
	private string _sch_subject;
	
	private string _sch_prof;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsch_idChanging(int value);
    partial void Onsch_idChanged();
    partial void Onsch_dayChanging(string value);
    partial void Onsch_dayChanged();
    partial void Onsch_dateChanging(string value);
    partial void Onsch_dateChanged();
    partial void Onsch_timeChanging(string value);
    partial void Onsch_timeChanged();
    partial void Onsch_classChanging(string value);
    partial void Onsch_classChanged();
    partial void Onsch_class_nameChanging(string value);
    partial void Onsch_class_nameChanged();
    partial void Onsch_subjectChanging(string value);
    partial void Onsch_subjectChanged();
    partial void Onsch_profChanging(string value);
    partial void Onsch_profChanged();
    #endregion
	
	public tbl_schedule()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sch_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int sch_id
	{
		get
		{
			return this._sch_id;
		}
		set
		{
			if ((this._sch_id != value))
			{
				this.Onsch_idChanging(value);
				this.SendPropertyChanging();
				this._sch_id = value;
				this.SendPropertyChanged("sch_id");
				this.Onsch_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sch_day", DbType="VarChar(50)")]
	public string sch_day
	{
		get
		{
			return this._sch_day;
		}
		set
		{
			if ((this._sch_day != value))
			{
				this.Onsch_dayChanging(value);
				this.SendPropertyChanging();
				this._sch_day = value;
				this.SendPropertyChanged("sch_day");
				this.Onsch_dayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sch_date", DbType="VarChar(50)")]
	public string sch_date
	{
		get
		{
			return this._sch_date;
		}
		set
		{
			if ((this._sch_date != value))
			{
				this.Onsch_dateChanging(value);
				this.SendPropertyChanging();
				this._sch_date = value;
				this.SendPropertyChanged("sch_date");
				this.Onsch_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sch_time", DbType="VarChar(50)")]
	public string sch_time
	{
		get
		{
			return this._sch_time;
		}
		set
		{
			if ((this._sch_time != value))
			{
				this.Onsch_timeChanging(value);
				this.SendPropertyChanging();
				this._sch_time = value;
				this.SendPropertyChanged("sch_time");
				this.Onsch_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sch_class", DbType="NChar(10)")]
	public string sch_class
	{
		get
		{
			return this._sch_class;
		}
		set
		{
			if ((this._sch_class != value))
			{
				this.Onsch_classChanging(value);
				this.SendPropertyChanging();
				this._sch_class = value;
				this.SendPropertyChanged("sch_class");
				this.Onsch_classChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sch_class_name", DbType="VarChar(50)")]
	public string sch_class_name
	{
		get
		{
			return this._sch_class_name;
		}
		set
		{
			if ((this._sch_class_name != value))
			{
				this.Onsch_class_nameChanging(value);
				this.SendPropertyChanging();
				this._sch_class_name = value;
				this.SendPropertyChanged("sch_class_name");
				this.Onsch_class_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sch_subject", DbType="VarChar(MAX)")]
	public string sch_subject
	{
		get
		{
			return this._sch_subject;
		}
		set
		{
			if ((this._sch_subject != value))
			{
				this.Onsch_subjectChanging(value);
				this.SendPropertyChanging();
				this._sch_subject = value;
				this.SendPropertyChanged("sch_subject");
				this.Onsch_subjectChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sch_prof", DbType="VarChar(100)")]
	public string sch_prof
	{
		get
		{
			return this._sch_prof;
		}
		set
		{
			if ((this._sch_prof != value))
			{
				this.Onsch_profChanging(value);
				this.SendPropertyChanging();
				this._sch_prof = value;
				this.SendPropertyChanged("sch_prof");
				this.Onsch_profChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
